### ISSUE TITLE
integration tests fail on master branch

### ISSUE THREAD

**Issue by dnav** [eclipse/leshan#352] opened 2017-06-15 07:53 UTC
Hi,

I tried to build all packages on a clean leshan repo and got this failure:
```
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ leshan-integration-tests ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.leshan.integration.tests.DeleteTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.171 sec - in org.eclipse.leshan.integration.tests.DeleteTest
Running org.eclipse.leshan.integration.tests.CreateTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 10.169 sec - in org.eclipse.leshan.integration.tests.CreateTest
Running org.eclipse.leshan.integration.tests.DiscoverTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.756 sec - in org.eclipse.leshan.integration.tests.DiscoverTest
Running org.eclipse.leshan.integration.tests.ExecuteTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.484 sec - in org.eclipse.leshan.integration.tests.ExecuteTest
Running org.eclipse.leshan.integration.tests.ObserveTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.011 sec - in org.eclipse.leshan.integration.tests.ObserveTest
Running org.eclipse.leshan.integration.tests.BootstrapTest
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.402 sec <<< FAILURE! - in org.eclipse.leshan.integration.tests.BootstrapTest
bootstrapSecure(org.eclipse.leshan.integration.tests.BootstrapTest)  Time elapsed: 3.037 sec  <<< FAILURE!
java.lang.AssertionError
	at org.eclipse.leshan.integration.tests.BootstrapTest.bootstrapSecure(BootstrapTest.java:73)

Running org.eclipse.leshan.integration.tests.RegistrationTest
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.512 sec <<< FAILURE! - in org.eclipse.leshan.integration.tests.RegistrationTest
register_observe_deregister_observe(org.eclipse.leshan.integration.tests.RegistrationTest)  Time elapsed: 1.169 sec  <<< FAILURE!
java.lang.AssertionError
	at org.eclipse.leshan.integration.tests.RegistrationTest.register_observe_deregister_observe(RegistrationTest.java:231)

Running org.eclipse.leshan.integration.tests.WriteTest
Tests run: 44, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.149 sec - in org.eclipse.leshan.integration.tests.WriteTest
Running org.eclipse.leshan.integration.tests.ReadTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.996 sec - in org.eclipse.leshan.integration.tests.ReadTest
Running org.eclipse.leshan.integration.tests.SecurityTest
2017-06-14 18:36:32,150 ERROR o.e.l.c.s.RegistrationEngine [RegistrationEngine#0] Registration failed: FORBIDDEN .
2017-06-14 18:36:32,181 ERROR o.e.l.c.s.RegistrationEngine [RegistrationEngine#0] Trying to bootstrap device but there is no bootstrap server config.
2017-06-14 18:36:41,486 ERROR o.e.l.c.s.RegistrationEngine [pool-1-thread-3] Deregistration failed: Timeout.
Tests run: 18, Failures: 0, Errors: 0, Skipped: 10, Time elapsed: 15.558 sec - in org.eclipse.leshan.integration.tests.SecurityTest

Results :

Failed tests: 
  BootstrapTest.bootstrapSecure:73 null
  RegistrationTest.register_observe_deregister_observe:231 null

Tests run: 119, Failures: 2, Errors: 0, Skipped: 13

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] leshan ............................................. SUCCESS [  1.490 s]
[INFO] leshan - core ...................................... SUCCESS [01:32 min]
[INFO] leshan - core californium .......................... SUCCESS [  6.615 s]
[INFO] leshan - server core ............................... SUCCESS [ 32.088 s]
[INFO] leshan - server californium ........................ SUCCESS [ 26.750 s]
[INFO] leshan - server cluster ............................ SUCCESS [ 47.714 s]
[INFO] leshan - client core ............................... SUCCESS [ 23.897 s]
[INFO] leshan - client californium ........................ SUCCESS [ 10.188 s]
[INFO] leshan - integration tests ......................... FAILURE [ 38.486 s]
[INFO] leshan - server demo ............................... SKIPPED
[INFO] leshan - client demo ............................... SKIPPED
[INFO] leshan - bootstrap server demo ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:43 min
[INFO] Finished at: 2017-06-14T18:36:45+02:00
[INFO] Final Memory: 32M/86M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project leshan-integration-tests: There are test failures.
```

My exact steps were:
git clone https://github.com/eclipse/leshan.git
cd leshan
mvn clean install

maven version output is:
```
mvn --version
Apache Maven 3.3.3 (NON-CANONICAL_2015-07-10T12:37:52_mockbuild; 2015-07-10T14:37:52+02:00)
Maven home: /usr/share/maven
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b16.fc23.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.8.13-100.fc23.x86_64", arch: "amd64", family: "unix"
```

Regards

**Comment by sbernard31** [comment] 2017-06-15 09:56
I tested it on my side and it works for me. We face some instability with integration tests #323 ... Sometimes you need to relaunch it  ... We currently have no idea about what happened :( 

Tell us if your problem persist after some retries.

**Comment by kanhab97** [comment] 2017-06-16 06:03
i tried this stuffs on my side, even it gives me someetimes this error , then i removed the integration test from pom file:
<module>leshan-integration-tests</module>
just remove this line for the time being.
again give the cmd mvn install/ mvn clean install
it will work fine..
after succesfully run, again add the same thing in the pom and again give the cmd mvn install,
it works for me, hope it will work

**Comment by sbernard31** [comment] 2017-06-22 13:19
@dnav did you success with some retry ?  Could we close this issue (as duplicate of  #323)?

**Comment by dnav** [comment] 2017-06-26 08:19
Hi,

It always fails on my setup. No matter the number of retries (clean or incremental).
I workaround the issue like @kanhab97 did.

This issue is a duplicate of #323 indeed.

Regards,

**Comment by sbernard31** [comment] 2017-06-27 13:26
It fails all the time ? You make me dream, this means on your configuration that's a reproducible issue :heart_eyes: !

Could you give us more detail about your configuration ? You give us everything at software side, what about hardware side ?

**Comment by dnav** [comment] 2017-06-27 14:40
This is a vmware virtual machine on a windows 10 host...
**If I can found some time** I may be able to provide you a disk image.

**Closed** 2017-07-31 13:44 UTC

**Comment by sbernard31** [comment] 2017-09-04 16:36
@dnav this should be fixed in master.
If you still have the VM which always fails the build and if you find time, I will appreciate that you check if its fixed for you :)
