### ISSUE TITLE
Bootstrap server time restriction between bootstrap retries

### ISSUE THREAD

**Issue by dtod21** [eclipse/leshan#1012] opened 2021-05-15 12:40 UTC
I noticed a possible bug while testing Leshan Bootstrap Server version 2.x.
The bootstrapping works without problem on the first attempt. If the device tries to bootstrap again within 4 minutes after a successful bootstrapping, it fails. The device sends a POST to the bootstrap server to the resource ''/bs'' with the corresponding parameters. The server also acknowledges this POST with a CHANGED (204). After that the bootstrap server should perform a DELETE on object 0 and 1. After the DELETE the bootstrap server should execute a PUT on these two objects. However, the DELETE and the PUT are not executed. If the server is restarted, a successful bootstrapping can be performed again. Alternatively, 4 minutes can be waited between bootstrapping attempts.

**Comment by sbernard31** [comment] 2021-05-17 08:13
Just to be clear you are using Leshan Bootstrap server **demo** ? which version exactly ? 

Reading the code I can not explain this behavior :thinking: 
I tried to reproduce it locally but I'm able to do 2 bootstrap in less than 4 minutes with same device using Leshan Client Demo. So it works for me. :grimacing: 

What are you using at client side ? Are you using DTLS ? 
Do you have any wireshark/tcpdump capture ? or logs ?

**Comment by boaks** [comment] 2021-05-17 08:20
> 4 minutes

Smells for `EXCHANGE_LIFETIME` default's 247s. So, guess, the starting requests are using the same MID.

**Comment by sbernard31** [comment] 2021-05-17 08:28
> Smells for EXCHANGE_LIFETIME default's 247s. So, guess, the starting requests are using the same MID.

Good candidate. 
The 2nd CHANGED (204) response sent by the server would be a retransmission handled by californium.
And So Leshan never get "the second Bootstrap Request" (because the stack consider it as a duplicate) and so Leshan never start the second bootstrap session.

**Comment by sbernard31** [comment] 2021-05-17 08:38
Maybe not so clear but this means that the bug would be at client side. 
A wireshark capture could confirm this.

**Comment by dtod21** [comment] 2021-05-17 16:09
> Just to be clear you are using Leshan Bootstrap server demo ? which version exactly ?

I am using Bootstrap Server demo. I don’t have found the specific version. The version which I am using was downloaded on 04 May as lastSuccessfulBuild from ci.eclipse.org.
> What are you using at client side ? Are you using DTLS ?

As client I use a STM32 uC, which runs the Wakaama example from the RIOT-OS project.  DTLS is not used.

> So, guess, the starting requests are using the same MID.

Yes, the MID is the same for both requests. I need to take a closer look at how the MID is generated. Even 5 minutes later the same MID is used.

Here are the packets which were captured with wireshark.
<img width="1452" alt="1" src="https://user-images.githubusercontent.com/84230772/118519676-9e319300-b739-11eb-858c-8f2c24a70971.png">
<img width="1452" alt="2" src="https://user-images.githubusercontent.com/84230772/118519697-a4277400-b739-11eb-8e62-b1e30edd586e.png">
<img width="1452" alt="3" src="https://user-images.githubusercontent.com/84230772/118519713-a7bafb00-b739-11eb-9f67-596bd069f7a0.png">
<img width="1452" alt="4" src="https://user-images.githubusercontent.com/84230772/118519722-aa1d5500-b739-11eb-89bb-0777086703ae.png">

Thanks a lot for your help.

**Comment by boaks** [comment] 2021-05-17 16:19
Do you restart the device?
If so, maybe the coap-library you use offers a function to set a initial (real-random?) MID.

**Comment by sbernard31** [comment] 2021-05-19 09:09
@dtod21 should we close this issue ?

**Comment by dtod21** [comment] 2021-05-19 16:15
> Do you restart the device?

Yes, I have restarted the device.

> should we close this issue ?

Yes, it can be closed. 

Thanks for the support.

**Comment by sbernard31** [comment] 2021-05-19 16:33
> Thanks for the support.

You're welcome ;)

**Closed by sbernard31** 2021-05-19 16:33 UTC
Labels: question
