### ISSUE TITLE
Is ObserveRequest need payload

### ISSUE THREAD

**Issue by BruceZhangXL** [eclipse/leshan#781] opened 2019-12-20 06:21 UTC
```java 
lwM2mServer.getRegistrationService().addListener(new RegistrationListener() {
            @Override
            public void registered(Registration registration, Registration previousReg, Collection<Observation> previousObsersations) {
            ObserveRequest request = new ObserveRequest(CHANNEL_ID, 0, 0);
                        lwM2mServer.send(registration, request,lifeTimeInMillSec, observeResponse ...);
    }
}
```

**I send ObserveRequest to the client,but exception throwed like this**

```
java.lang.IllegalArgumentException: The validated object is null
        at org.eclipse.leshan.util.Validate.notNull(Validate.java:222)
        at org.eclipse.leshan.util.Validate.notNull(Validate.java:205)
        at org.eclipse.leshan.core.node.LwM2mSingleResource.<init>(LwM2mSingleResource.java:38)
        at org.eclipse.leshan.core.node.LwM2mSingleResource.newBinaryResource(LwM2mSingleResource.java:106)
```
code in class CoapRequestBuilder , **no set payload**

```java 
   @Override
    public void visit(ObserveRequest request) {
        coapRequest = Request.newGet();
        if (request.getContentFormat() != null)
            coapRequest.getOptions().setAccept(request.getContentFormat().getCode());
        coapRequest.setObserve();
        setTarget(coapRequest, request.getPath());

        // add context info to the observe request
        coapRequest.setUserContext(ObserveUtil.createCoapObserveRequestContext(endpoint, registrationId, request));
    }
```

Whether a problem?

**Comment by sbernard31** [comment] 2019-12-30 14:14
It seems that the binary value returned by the device is `null`... :male_detective: 
is it the expected behavior ? I mean : does the resource /CHANNEL_ID/0/0 is equals to `null` or an `empty byte array` at device side ?

Maybe we do not support this correctly, I will check this one my side.

I suspect the stacktrace is not complete, could you please share the full error stacktrace ?

(By the way I have doubt that this error was raised in `CoapRequestBuilder` :thinking: ...)

**Comment by sbernard31** [comment] 2019-12-30 15:56
(If you have a wireshark capture this could help too)

**Comment by sbernard31** [comment] 2019-12-31 13:26
I pushed a commit (d44a562) which should fix an issue with empty value when using OPAQUE content format.
I'm not sure this is directly link to your issue.

**Comment by sbernard31** [comment] 2020-01-06 15:31
Should it fixed your issue could we close this one ?

**Comment by sbernard31** [comment] 2020-01-13 15:12
Do not hesitate to reopen if the issue is still here.

**Closed by sbernard31** 2020-01-13 15:12 UTC
Labels: question
