### ISSUE TITLE
stress test

### ISSUE THREAD

**Issue by liutianyuan** [eclipse/leshan#1179] opened 2021-12-13 10:22 UTC
Is there any information about the stand-alone  server stress test?
Thanks.

**Comment by sbernard31** [comment] 2021-12-13 10:23
What are you calling the stand-alone server ?

**Comment by liutianyuan** [comment] 2021-12-14 00:58
> What are you calling the stand-alone server ?
Thank you for your promptly response.
I have started a single leshan server runing on a cloud server(8core,3.0G,16G). And a leshan client on another cloud server. I used the latest master branch with UDP and not using Queue mode.

I want to do a stress test about the concurrency of the leshan server.
Question 1: How to do this stress test correctly?
Question 2: Is there any performance benchmarks about leshan server?
Question 3:  In the actual scenario, we have about 100,000+ endpoints to send data concurrently,  I want to evaluate if a single leshan server can hold Or cluster server? 

Sorry for my pool English and Thank you in advance.

**Comment by boaks** [comment] 2021-12-14 06:14
Just in the case, that you're also interested in testing CoAP/DTLS on its own, you may also open an issue in [eclipse/californium](https://github.com/eclipse/californium/issues).

**Comment by liutianyuan** [comment] 2021-12-20 00:56
@boaks  @sbernard31 
Sorry for replying so late. Thank you for your kind reply and constructive advice. I will continue to follow up this task.
The [benchmark-clients](https://github.com/sbernard31/benchmark-clients) is wonderful  and helpful. Thank you again.

**Comment by boaks** [comment] 2021-12-20 09:53
@liutianyuan 

Just in the case you're allowed to publish the results, I'm interested in.
My own benchmarks, the performance of a 4x1.5 GHz Silver Pentium is about 30.000 coaps-request/s.
(See [Eclipse/Californium - coap-benchmark](https://github.com/eclipse/californium/tree/master/demo-apps/cf-extplugtest-server#benchmarks) )

**Comment by sbernard31** [comment] 2022-01-07 10:34
@liutianyuan do not hesitate to share any result with us :pray:

**Comment by liutianyuan** [comment] 2022-03-14 08:40
> @liutianyuan do you plan to share any result ? if not I think we can close this one ?

Sorry for late response. For some reason  we have changed to MQTT finally.

Thank you very much for your kind help.

**Comment by sbernard31** [comment] 2022-03-14 09:33
Thx to let you know that. I close this issue. 

> For some reason we have changed to MQTT finally.

I'm curious, if you can/want please share the reason here (even if the issue is closed)

**Closed by sbernard31** 2022-03-14 09:33 UTC
Labels: question
