### ISSUE TITLE
client re-registration causes server to empty its queue

### ISSUE THREAD

**Issue by chuchiliusandc** [eclipse/leshan#207] opened 2016-11-28 21:15 UTC
When client tries to re-register,
server will empty its queue.

I feel if both previous registration and current registration were Q mode, its queue shouldn't be emptied.

Thanks :)

**Comment by chuchiliusandc** [comment] 2016-11-29 00:30
If update failed (e.g., timeout), device will try to re-register.

**Comment by sbernard31** [comment] 2016-11-29 11:06
I think you talk about 2 different issue here. Next time please open 2 issue :) 
1) we empty queue on register. (there is no difference between register and re-register)
2) client try to register after a failing update.

About 1), that was the behavior described in the spec when we implement QueueMode. But the spec is now different and we will probably refactor the QueueMode a lot.

About 2), what behavior did you expect ?

**Comment by chuchiliusandc** [comment] 2016-11-29 18:09
I just feel, in my case, the device won't start without registration.
However, after the registration, if the device is not able to talk to server.
It will be trying to register again. (Q: Since it cannot update, why does device think it can still register ?)

If it did succeed in 2nd registration, I feel, in this case, we shouldn't empty the previous queue if its mode still contains Q mode. Will the new design keep the previous Queue ?

One more question here ... Is the ACK_TIMEOUT value on client side from the ACK_TIMEOUT value on the server side ? or client and server can have totally different ACT_TIMEOUT ?

Thx :)

**Comment by sbernard31** [comment] 2016-11-30 13:26
The LeshanClient does really support QueueMode.
> Q: Since it cannot update, why does device think it can still register ?

Because a server can refuse an update (e.g. it lost the registration) and accept a new registration.
Please, Could you explain which behavior you expect ?

In the new design there is no queue anymore. See #191  for more details. (you can also read the last version of the spec)

About ACK_TIMEOUT, this is a CoAP question. To be honest it's not clear for me. You could have a look at the [CoAP spec](https://tools.ietf.org/html/rfc7252#section-4.8.1). You can also send your question on [Californium mailing list](https://dev.eclipse.org/mailman/listinfo/cf-dev) or [IETF Core mailing list](https://www.ietf.org/mailman/listinfo/core).

**Comment by chuchiliusandc** [comment] 2016-11-30 22:20
Hi Sbernard31,

(1/2)
From my observation, the leshan server supports QueueMode.
However, for the leshan client, I was not able to get it to sleep after waiting for ACK_TIMEOUT.
That is why I feel the client didn't have QueueMode thing implemented.
(Reference: Candidate spec, version 1.0 - 07 Apr 2016, 
page 71, fig 23: Example of Device Management & Service Enablement interface exchange for Q Mode
page 72, fig 24: Example of an Information Reporting exchange for Q Mode.)

(2/2)

For the client, I was thinking, if it failed to update due to some server/network issues,
can the client try couples of updates before doing the register again ?

And, for the server, can it check if the device had being registered ? if still registered and queue not empty, can the server just reuse the old queue and old registration data ?

Thanks :)

**Comment by sbernard31** [comment] 2016-12-01 11:10
(1/2) Sry, I meaned  _"The LeshanClient ~~does~~ doesn't really support QueueMode."_
(2/2) In fact this is already the case, as there is severals [CoAP retransmission](https://tools.ietf.org/html/rfc7252#section-4), but we can probably do something clever. For now, we are not too much focused on Leshan Client, but we can review PR :). Before coding, maybe starting a discussion about this on the Leshan mailing list (or even on wakaama mailing list too) would be a good start.

For the server, with the new implementation this will be up to the server to decide how it manage that.

**Comment by chuchiliusandc** [comment] 2016-12-02 00:29
Thanks :)

**Comment by chuchiliusandc** [comment] 2016-12-02 18:32
Hi sbernard31,

I just think of something and wanna to be clear about something here, so I just reopen this one. 
Sorry about that. 

(1/2)
I see :)
No wonder I never see client to be in the sleep mode after ACK_TIMEOUT.

(2/2)
You said "For the server, with the new implementation this will be up to the server to decide how it manage that.". 
I think you mean, in the new implementation provided by leshan eclipse, 
the leshan server can be configured to how to manage the registration of the client who had previously registered ? can cancel the pending requests or can reuse the pending requests ?

Thanks :)

**Comment by chuchiliusandc** [comment] 2016-12-03 03:07
Hi,

(3/3)
I am looking at QueueModeTest.java for the queue mode integration test.
There seems to be a bug on cancel_pending_throws_exception_for_first_message_and_doesnot_send_others.
It has responseCountDownLatch to be 2 initially.
Shouldn't it be 1 initially ?
Although I don't know why it still succeed with 2 ...

Thx

**Comment by sbernard31** [comment] 2016-12-05 13:16
(2/2) For more explanation see #191
(3/3) I already see some strange things in this tests but I didn't take time to clean this because we will probably change it a lot with the new implementation.

**Comment by balsmn** [comment] 2016-12-05 13:49
Actually the _responseCountDownLatch_ is set to 1 and only the _unexpectedResponseCountDownLatch_ is set to 2. As the test case specifies, once the first request in the queu is cancelled(which as per test case will be in coap retry mode), an exception should be thrown for the same and further requests in the Queue should not be sent.

**Comment by chuchiliusandc** [comment] 2016-12-05 22:45
HI balsmn, 

(1/3)
I don't think responseCountDownLatch is set to 1.
It is set to 2. (see the code I got from the eclipse leshan github below).
`    @Test
    public void cancel_pending_throws_exception_for_first_message_and_doesnot_send_others() throws Exception {
        final CountDownLatch exceptionCountDownLatch = new CountDownLatch(1);
        final CountDownLatch responseCountDownLatch = new CountDownLatch(2);
        final CountDownLatch unexpectedResponseCountDownLatch = new CountDownLatch(2);`

It is 2, but it still succeed. Same as you, I think it should be 1 instead.
Moreover, it did still suc with 2 ... so strange ... I don't know why 2 still suc.

(2/3)
I also fond a typo on line 252.
It has `        // Wait for read request timeout`
I should be observe request since it is right after an observe request.

(3/3)
I also found a bug in the method,
 all_requests_sent_if_client_reachable().
`        responseListener = new ResponseListener() {
            @Override
            public void onResponse(Client client, String requestTicket, LwM2mResponse response) {
                if (response instanceof WriteResponse) {
                    LOG.trace("Received write response for ticket {} from LWM2M client {}", requestTicket, response);
                    acceptCountDownLatch.countDown();
                    assertEquals(ResponseCode.CHANGED, response.getCode());
                }
            }

            @Override
            public void onError(Client client, String requestTicket, Exception exception) {
                throw new IllegalStateException("unexpected exception occurred: ", exception);
            }
        };
        helper.server.getLwM2mRequestSender().addResponseListener(responseListener);
        helper.server.getLwM2mRequestSender().send(helper.getCurrentRegistration(), TEST_REQUEST_TICKET + "3",
                new ReadRequest(3, 0, 1));`
Here, read request is sent out.
However, the resposneListener is trying to test for WriteResponse.
There is no write request being sent after this read request.
I think something must be wrong...

Hi sbernard31,

(2/2)
Just want to make sure I get this right.
In coap level, MAX_RETRANSMIT is the max number of tries, althrough it appears to be one REGISTER or UPDATE request in lwm2m level, a upper level.

MAX_TRANSMIT_WAIT=93000
MAX_RETRANSMIT=4

And, for MAX_TRANSMIT_WAIT, it is the time to wait between each try in coap level.
Do I understand correctly ?

(3/3)
Understood.

Thanks and The inputs from you guys are really helpful :) clear lots of thing for me ^0^

**Comment by balsmn** [comment] 2016-12-06 09:46
@chuchiliusandc
(1/3) : Sorry I was on a different branch and read it wrong. My bad. Yes, I see it 
https://github.com/eclipse/leshan/blob/master/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/QueueModeTest.java#L528

If set to 2, until it reaches 0, the client will not respond to the requests. Thats why the test case is working as the unexpected responses are never sent. Yes it should have been 1 but that will introduce the timing problem I mentioned above.

(3/3): The intention of the test case is to make sure that the Queue is empty when the client is in reachable state and so the check for `ReadResponse ` is missing. Actually not a bug. The write request is sent as the second request after observe.
https://github.com/eclipse/leshan/blob/master/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/QueueModeTest.java#L316

Anyways, I reworked the test case listeners and hope this helps you. 


    public void all_requests_sent_if_client_reachable() throws Exception {
        TestObservationListener listener = new TestObservationListener();
        helper.server.getObservationRegistry().addListener(listener);
        QueuedModeLeshanClient client = (QueuedModeLeshanClient) helper.client;

        final CountDownLatch observeRequestCountDownLatch = new CountDownLatch(1);
        final CountDownLatch writeRequestCountDownLatch = new CountDownLatch(1);
        final CountDownLatch readRequestCountDownLatch = new CountDownLatch(1);

        // prepare expectations
        responseListener = new ResponseListener() {
            @Override
            public void onResponse(Client client, String requestTicket, LwM2mResponse response) {
                if (response instanceof ObserveResponse) {
                    LOG.trace("Received observe response for ticket {} from LWM2M client {}", requestTicket, response);
                    Observation observation = ((ObserveResponse) response).getObservation();
                    observeRequestCountDownLatch.countDown();
                    assertEquals("/3/0/15", observation.getPath().toString());
                    assertEquals(helper.getClient().getRegistrationId(), observation.getRegistrationId());
                }
                if (response instanceof WriteResponse) {
                    LOG.trace("Received write response for ticket {} from LWM2M client {}", requestTicket, response);
                    writeRequestCountDownLatch.countDown();
                    assertEquals(ResponseCode.CHANGED, response.getCode());
                }
                if (response instanceof ReadResponse) {
                    LOG.trace("Received write response for ticket {} from LWM2M client {}", requestTicket, response);
                    readRequestCountDownLatch.countDown();
                    assertEquals(ResponseCode.CONTENT, response.getCode());
                }
            }

            @Override
            public void onError(Client client, String requestTicket, Exception exception) {
                throw new IllegalStateException("unexpected exception occurred: ", exception);
            }
        };
        helper.server.getLwM2mRequestSender().addResponseListener(responseListener);
        // set client to respond to GET
        client.setOnGetCallback(respondOnGet);
        // Send an Observe request
        helper.server.getLwM2mRequestSender().send(helper.getClient(), TEST_REQUEST_TICKET + "1",
                new ObserveRequest(3, 0, 15));
        // write device timezone.
        helper.server.getLwM2mRequestSender().send(helper.getClient(), TEST_REQUEST_TICKET + "2",
                new WriteRequest(3, 0, 15, "Europe/Berlin"));
        // send read request
        helper.server.getLwM2mRequestSender().send(helper.getClient(), TEST_REQUEST_TICKET + "3",
                new ReadRequest(3, 0, 1));

        waitForInterval(TIMEOUT);
        assertQueueIsEmpty(5000L);
        assertTrue("Expected ObserveResponse but did not receive one.",
                observeRequestCountDownLatch.await(1, TimeUnit.SECONDS));
        assertTrue("Expected WriteResponse but did not receive one.",
                writeRequestCountDownLatch.await(1, TimeUnit.SECONDS));
        assertTrue("Expected ReadResponse but did not receive one.",
                readRequestCountDownLatch.await(1, TimeUnit.SECONDS));

        // wait for notify
        listener.waitForNotification(2000);
        assertTrue(listener.receievedNotify().get());
    }

**Comment by sbernard31** [comment] 2016-12-06 10:25
(2/2) MAX_TRANSMIT_WAIT is the maximum time from the first transmission of a Confirmable message to the time when the sender gives up on receiving an acknowledgement or reset.

**Comment by chuchiliusandc** [comment] 2016-12-06 19:10
Hi sbernard31,

(2/2)

Thanks. I assume I understood the meaning of MAX_RETRANSMIT successfully.

For MAX_TRANSMIT_WAIT, 
I thought that is ACK_TIMEOUT.
Because I was setting ACK_TIMEOUT to a very small value, the client failed to register due to the timeout.  So, you means MAX_TRANSMIT_WAIT is the same as ACK_TIMEOUT except MAX_TRANSMIT is for confirmable message ?
Could you give an concrete example of Confirmable message ? 

Hi balsmn,

(1/3) 

At line 557, it has the comment, "client will start responding from this point.".
i.e., `        responseCountDownLatch.countDown(); // client will start responding from this point.
        assertQueueIsEmpty(3000);`
That is why I think it should be 1 (as you agreed), but it is 2.
That means there will be no responses from client.
However, the assertQueueIsEmpty did pass ... (This method runs successfully.)
The requests in the queue should never be removed unless their responses are received.
Therefore, I am confused about why it still succeed.
assertQueueIsEmpty passed ... i means the two previous 2 read requests are no longer there ...
but there are no responses since client is not responding (i.e.. return false (see createConditionalResponseOnGet))

One more thing,
I didn't see any places that will cause exceptionCountDownLatch to be counted down in the code.
There is no client.stop(true) in this method.

(3/3)
I don't agree about this is not a bugs.
If you put a break point in between line 327 to 329 in method, all_requests_sent_if_client_reachable.
then you will find out these 3 lines that handles write response are never executed.
However, you change it from writeResponse to readResponse (line 326).
Then, you will begin to see the line 327 to line 329 get executed.

Thanks ^_^

**Comment by balsmn** [comment] 2016-12-07 10:10
(1/3) I think you are reading the test case wrong. It is actually testing the server side implementation of CANCEL. If pending messages are cancelled, all messages will be removed from Queue and hence passed.

Client is not stopped ofcourse here. It is part of the TestCase setup.
https://github.com/eclipse/leshan/blob/master/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/QueueModeTest.java#L107

**Comment by chuchiliusandc** [comment] 2016-12-08 00:32
(2/2) pending

(1/3) Thanks, balsmn :) I think I get it now. I was confused by this comment, 
"// client will start responding from this point.", client will never respond in this test case since there is only one count down ... 

(3/3) pending

**Closed** 2017-01-06 14:51 UTC
