### ISSUE TITLE
Location object is not working(Time out)

### ISSUE THREAD

**Issue by Ross1503** [eclipse/leshan#646] opened 2019-01-28 10:41 UTC
Hi sbernard31,,
when i am connecting lwm2m client with lwm2m server through bootstrap server, location object is not working, any resource query of location object is getting Time out. in other hand if we connect lwm2m client with lwm2m server directly(withoutr Bootstrap server) location object works properly(responding with proper values for any resource query of location object). 
Is there any specific limitation on server side for above behaviour?

**Comment by sbernard31** [comment] 2019-01-28 14:17
When you talk about "lwm2m client with lwm2m server through bootstrap server".
I suppose you mean leshan-client-demo, leshan-server-demo and leshan-bsserver-demo ?

I just tested it on my side with master and it works for me.
without more precise information to try to reproduce I can not really help.

**Comment by Ross1503** [comment] 2019-02-08 03:49
Hi sbernard31,
Thanks for your response.
But still i am getting timeout for location object resource. few things i've observed:
1. when i am connecting direct  to "leshan-server-demo" without using "leshan-bsserver-demo", during registration "leshan-client-demo" sends objects list as "</1/0>,</2/0>,</3/0>,</4/0>,</5/0>,</6/0>,</7/0>,</9>,</15> ".
2. BUT when i am using connection through "leshan-bsserver-demo", During registration "leshan-client-demo" sends objects list to  "leshan-server-demo" as  "</1/0>,</2>,</3/0>,</4>,</5>,</6>,</7>,</9>,</15> "
As you can see the  difference in both the objects list, in second case it is not sending the instance id with object id of object /2,/4,/5,/6,/7,(particularly "/6"). this is the reason i am getting time-out for those resources.is there any limitation on the BS side?
and one more query lwm2m server is getting SSID as 123 & Lt as 20, may i know  from where lwm2m server resources  are getting those values?

**Comment by sbernard31** [comment] 2019-02-08 14:38
It looks like all the instance was removed after the bootstrap.

Which version of Leshan are you using ? because Leshan client should only [delete security and server object](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M10/leshan-client-core/src/main/java/org/eclipse/leshan/client/servers/BootstrapHandler.java#L72) ... and it seems that you have no instance for object 2 (server) ... this is very surprising.

> this is the reason i am getting time-out for those resources.is there any limitation on the BS side?

This sounds not "normal" but you should not get a timeout a NOT FOUND response or something like this.

**Comment by sbernard31** [comment] 2019-02-20 14:36
Should we close this issue ?

**Closed** 2019-03-08 10:38 UTC
Labels: question
