### ISSUE TITLE
Bootstrap Server 2.0.0-M5 upgrade: problem with ConnectionListener

### ISSUE THREAD

**Issue by gerardolenski** [eclipse/leshan#1191] opened 2022-01-04 12:10 UTC
Hi guys.

I'm upgrading the Bootstrap Server from `2.0.0-M4` to `2.0.0-M5`. In my server configuration, I have the `ConnectionListener` registered in `DtlsConnectorConfig`. My implementation listens to the `void onConnectionRemoved(Connection connection)` event to handle DTLS connection error. 

In version `M4` I invoked `connection.getSession()` and `connection.getOngoingHandshake()` to gather some detailed information of the DTLS session. However in `M5` the both methods return `null` instead of correct objects. 

For me, it looks like a regression. Can you please advise?

**Comment by sbernard31** [comment] 2022-01-05 09:16
This looks like to be relative to Californium/Scandium not directly to Leshan.
From 2.0.0-M4 to 2.0.0-M5 we migrate from Californium/Scandium 2.6.3 to 3.0.0-RC1 so maybe there is a regression or a behavior change. You should open a bug at : https://github.com/eclipse/californium/issues to get more information.

**Comment by gerardolenski** [comment] 2022-01-05 11:43
Oh right, I raised an issue at californium: https://github.com/eclipse/californium/issues/1868

BTW. I also verified that in the official `3.0.0` californium version this problem still occurs.

**Comment by gerardolenski** [comment] 2022-01-07 20:23
I'd like to summarize to give feedback. The Eclipse Californium Scandium v. `3.0.0` was cleaned and now the `Connection` object in `ConnectionListener` interface behaves differently. The reason for that was found by the contributor, but it won't be restored. Instead of that, in `californum/scandium` v. `3.2.0` the `SessionListener` interface will be added to `DtlsConnectorConfig` which will better works as a DTLS session lifecycle listener.

Pls see [#1870](https://github.com/eclipse/californium/issues/1870) for release details.

Is it possible to plan a `californium` dependency upgrade in Leshan v2 from `3.0.0.-RC1` to `3.2.0`?

**Comment by sbernard31** [comment] 2022-01-10 08:49
Yep this will done :)

**Comment by sbernard31** [comment] 2022-01-10 08:53
Do you also need a milestones release of Leshan soon ?

**Comment by sbernard31** [comment] 2022-01-10 10:59
Ok so even if that was not plan, I will consider to release a 2.0.0-M6 soon.

As soon as cf 3.2.0 will be integrated in `master`, could you test/play with `master` to be sure this version works for you ?

**Comment by gerardolenski** [comment] 2022-01-10 17:37
Yes, of course I'll do it and let you know. Many thanks.

**Comment by boaks** [comment] 2022-01-13 10:45
Californium 3.2.0 is available - happy testing.

**Comment by sbernard31** [comment] 2022-01-13 14:21
@gerardolenski, 

Californium 3.2.0 is now integrated in `master`.
I will force the nightly build to make it available sooner so you will be able to test it.
(I will let you know when I think it is ready)

I looked at https://github.com/eclipse/californium/issues/1868, and see that you mainly need a `SessionListener`. 
Do you try [this way to attach a `SessionListener`](https://github.com/eclipse/leshan/blob/leshan-2.0.0-M5/leshan-client-demo/src/main/java/org/eclipse/leshan/client/demo/LeshanClientDemo.java#L223L293) ?
With this you maybe not even need a new Leshan release as maybe this works with v2.0.0-M5.

Let me know about all of that.

**Comment by sbernard31** [comment] 2022-01-13 14:25
[Nightly of `master`](https://ci.eclipse.org/leshan/job/leshan-nightly/102/) (2.0.0-SNAPSHOT) should be available. (See  #885 for more details about how to use it)

**Comment by gerardolenski** [comment] 2022-01-13 14:41
Hi,

thank you. I'm testing now the new Californium 3.2.0 with Leshan 2.0.0-M5. And yes - I need `SessionListener` because the `ConnectionListener` behaves differently than in 2.0.0-M4. I introduced my own implementation of `SessionListener` using `DtlsConnectorConfig.Builder#setSessionListener(SessionListener sessionListener)` method which was added in Californium Scandium 3.2.0. And it works fine for me :)

**Comment by sbernard31** [comment] 2022-01-13 15:14
> But still, maybe this is not a bad idea to release the Leshan with the final v3 californium version? Because now you depend on the release candidate version, right?

The 2.0.0-M5 is a milestone release, so I think it's not really a problem to depends on Release Candidate.
In another hand : 
- We don't release 2.0.0-Mx version since end of October 2021. 
- Current work are about `oscore` and `some refactoring about Link Format`, 

Nothing which could be available at short term  for `master`,  so maybe this is the good timing for a 2.0.0-M6. 

Any chance that you could test the current nightly to be sure there is no obvious issue for you  before the release ?

**Comment by gerardolenski** [comment] 2022-01-14 07:51
Hi,

ok, no problem. I can test also the `master` with Eclipse `3.2.0`. Probably I can do it tomorrow.

**Comment by boaks** [comment] 2022-01-14 08:33
> Do you try this way to attach a SessionListener ?

I wasn't aware, that leshan is using that API for the demo as well. 
For Californium the issue I remembered was [Make it possible to register SessionListener instances in a custom subclass of DTLSConnector ](https://github.com/eclipse/californium/issues/716). There I asked, if the new way using the Configuration would also work. With the answer  there, I would like to deprecate the old API. At least I don't see to many advantages, to keep the old, the new one seems for me to be easier to use.

**Comment by sbernard31** [comment] 2022-01-14 08:58
> There I asked, if the new way using the Configuration would also work. 

I already switched to the new API yesterday : https://github.com/eclipse/leshan/commit/42c7fcf57bd79fa3ee6c32a0f8b160349a4c9154

I do a very quick check and it sounds to work.

**Comment by boaks** [comment] 2022-01-14 09:07
If the new doesn't work for some use-cases, it is also easy to remove the deprecation and keep it

**Comment by gerardolenski** [comment] 2022-01-14 11:59
I've tested Leshan `2.0.0-SNAPSHOT` with Californium `3.2.0`. Works fine for me.

**Comment by sbernard31** [comment] 2022-01-20 09:51
I guess we can close this one ?

**Closed** 2022-01-21 07:13 UTC
Labels: question
