### ISSUE TITLE
Leshan BS DTLS_Server boot incorrect error

### ISSUE THREAD

**Issue by 18715001062** [eclipse/leshan#1199] opened 2022-01-17 03:49 UTC
The BS_DTLS server will deliver the BS server, which will cause the client to frequently connect to the BS. This is incorrect. In the comparison test, we tried to connect to the ATT platform. We parsed the COAP packet and found that the BS delivered the DM server, not the BS server.

**Comment by sbernard31** [comment] 2022-01-17 08:54
What are you using at client and server side exactly ? are you using leshan library or leshan demo or something else ? which verison ? 

I will also need a better/precise explanation about what you achieve because I don't get you at all.  :confused: 

If you have a wireshark/tcpdump capture this could help to understand too.

**Comment by 18715001062** [comment] 2022-01-17 09:18
The client uses an IoT module, and the module itself supports the LWM2M protocol.
The server address is: **https://leshan.eclipseprojects.io/bs**
We open the server, add a BS client to the server, and the module writes the added configuration file to initiate registration to the leshan server. This is my test process.we also grabbed the wireshark packet. From the packet point of view, the object 0/0 sent by the BS server is still the BS server, which is incorrect. I don’t think it should be sent to the BS server repeatedly.

Attached is the wirshark file: 

[connected to leshanBS-wireshark.zip](https://github.com/eclipse/leshan/files/7880601/connected.to.leshanBS-wireshark.zip)

**Comment by boaks** [comment] 2022-01-17 09:27
1. you don't use DTLS at all
2. the BS provides 2 server, /0/0 the BS server itself, /0/1 the DM server
3. it's your device, which restarts the bootstrap

Why your module keeps on bootstrapping is left to your module. Maybe you can check the logs there.

**Comment by 18715001062** [comment] 2022-01-17 09:50
Thank you, there is another question, how to modify the BS java file in the leshan-master project to ensure that only the DM server is delivered, not the BS server

**Comment by boaks** [comment] 2022-01-17 09:53
Without BS your device may get dead. You won't have a chance to redo a bootstrap, e.g. in case where credentials are changing.

maybe you better fix the iot module.

**Comment by sbernard31** [comment] 2022-01-17 09:59
Maybe I missed something but just use the wizard  :thinking: : 
![Capture d’écran de 2022-01-17 10-52-35](https://user-images.githubusercontent.com/840294/149747513-576860e4-abc9-48e4-bafc-972dd2fbb87f.png)


------------------------------------

> Without BS your device may get dead.

This depends a lot about how much the device follow the spec. Theoretically it should not erase the bs server on delete /0.
So previous bs server should be kept. 
But the specification does prevent you to override it with a WRITE. (I still don't understand the point of the spec here :disappointed:)

I try to explain this in the wizard UI : 

> A LWM2M Bootstrap Session generally starts by deleting part of the existing configuration on the LWM2M client.
>
> By default, objects /0 and /1 are deleted, then you will be able to define LWM2M Server and LWM2M Bootstrap Server to add.
>
>Note that Security /0 Object Instance storing LWM2M Bootstrap server data can not be deleted using Delete Request.
>Adding Security instance without knowing the Instance ID of Bootstrap Server could lead to some unexpected behavior (see >[OMA#522](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/522), [OMA#523](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/523)).
>By default, this wizard use the convention that LWM2M Bootstrap Server Security instance ID is 0.
>If your client don't use this convention, you can use autoIdForSecurityObject=true and so Leshan will start the Bootstrap >session with a Discover request to know which Security instance ID is used for the Bootstrap Server.

**Comment by 18715001062** [comment] 2022-01-17 10:05
"autoIdForSecurityObject=true" in which file is this modified, I didn't find it

**Comment by 18715001062** [comment] 2022-01-20 05:32
hello，does Leshan have API interface documentation? I want to query the data reported by the client to the server

**Comment by sbernard31** [comment] 2022-01-20 08:52
I'm not sure to get the point. 

> I want to query the data reported by the client to the server

This issue is about bootstrap server and during a bootstrap session this is rather the server which send data to the client..

I don't get which API you are talking about.
If this is java API, there is nothing more than `getting` started and the javadoc. 
If this is about server demos, see :
 - https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-
 - https://github.com/eclipse/leshan/wiki/F.A.Q.#is-there-a-rest-api-for-leshan-server-demo-

**Comment by 18715001062** [comment] 2022-01-24 06:07
Hello, Client sends data to the leshan server, and it will be rejected by the server probabilistically. May I ask why? The server has subscribed and the client also responded. The first packet of data was successfully sent. After a while, the sent data was rejected by the server.

**Comment by 18715001062** [comment] 2022-01-24 07:05
[rst-leshan.zip](https://github.com/eclipse/leshan/files/7923360/rst-leshan.zip)

I also confirmed that the IP has not changed

**Comment by 18715001062** [comment] 2022-01-24 07:53
I found that the probability of the server sending RST messages is quite high. What is the server doing? I frequently receive RST messages from the server.

**Comment by boaks** [comment] 2022-01-24 08:30
In my experience, such RST for CON notifies are mainly caused by address changes. The nasty side of that is, that sometimes it's not the client, which changes the address, it's a component on the ip-route/path. Especially for RFC7641 (observe/notify), that precondition of stable ip-addresses too frequently turns out to fail for longer periods. To have a tool to detect such change, Eclipse/Californium has a "myip" resource, that respond with the client's ip-address visible to the server. Not sure, if the leshan project has interest to add that (it's out of scope of lwm2m, I only use it for diagnose), otherwise you may use coap and the Eclipse/Californium "californium.eclipseprojects.io" sandbox to find out, if something changes your address. Use 

```
GET coap://californium.eclipseprojects.io/myip
???.???.193.130:28???
```

and repeat that after such a quite period.

For Californium (in divergence and not compliant to RFC7252/RFC7641) we added therefore "scoped tokens", using them may help to overcome that. It requires additional an endpoint-context-matcher. For DTLS such a endpoint matching could be done using the principal, for plain UDP I guess, the used matcher will withdraw the notification and therefore send a RST.

(I would recommend, that you start using DTLS. And, maybe setup your own leshan sandbox.)

**Comment by 18715001062** [comment] 2022-01-24 08:38
What do you mean, if I use DTLS, I won't get the RST problem from the server?

**Comment by boaks** [comment] 2022-01-24 08:47
That depends on the used `EndpointContextMatcher`, so it's a question to the leshan team, which one the sandbox is using. And, if (upcoming) RFC9146 is not used, that usually requires a (resumption) handshake. In the past there have been a lot of discussion about [RFC7252 9.1.2](https://datatracker.ietf.org/doc/html/rfc7252#section-9.1.2), I'm not sure, what the outcome in LwM2M about that was.

**Comment by boaks** [comment] 2022-01-24 08:48
But first, I would recommend, that you check, if your client's address is really changed on the path. Hope you client is able to execute coap GET requests.

**Comment by 18715001062** [comment] 2022-01-24 08:53
I just connected to the leshan server using DTLS. After I sent a packet of data, I waited 5 minutes before sending the data. The server did not send an RST message. I still hope that the leshan team can optimize the non-DTLS scenario.

The server I am currently using: https://leshan.eclipseprojects.io/

**Comment by sbernard31** [comment] 2022-01-24 09:01
I still don't get how those question are related to this issue named  "Leshan BS DTLS_Server boot incorrect error": 

> hello，does Leshan have API interface documentation? I want to query the data reported by the client to the server

> Client sends data to the leshan server, and it will be rejected by the server probabilistically. May I ask why? The server has subscribed and the client also responded. The first packet of data was successfully sent. After a while, the sent data was rejected by the server.

So, please next time open 1 issue by subject ...

-----------------------------------------

I also think your last issue is about device IP changing (probably because of NAT or something like this)

> I still hope that the leshan team can optimize the non-DTLS scenario.

No this is not about optimization this is about following or not the RFC(s).
Here some documentation to read to better understand this : 
- https://github.com/eclipse/leshan/wiki/LWM2M-Observe#my-device-receive-rst-coap-message-
- https://github.com/eclipse/leshan/wiki/LWM2M-Observe#requestnotifications-matching

**Comment by boaks** [comment] 2022-01-24 09:03
> The server did not send an RST message

That may be also caused by just dropping your notification. So is the changed data shown in the leshan Web UI?

**Comment by 18715001062** [comment] 2022-01-24 09:06
> > 服务器没有发送 RST 消息
> 
> 这也可能是由于仅删除您的通知造成的。那么乐山Web UI中显示的数据是变化的吗？

Yes，Data is changing in real time

**Comment by boaks** [comment] 2022-01-24 09:18
Just to mention:
In my experience, using plain coap (without dtls) is not recommended for the public internet.
It is more common in private networks with less security considerations/constraints. e.g. a NB-IoT device and a vpn-ip-tunnel to your server. But not for general.

**Comment by sbernard31** [comment] 2022-02-11 08:57
Could we close this one ?

**Comment by 18715001062** [comment] 2022-02-11 09:12
yes. thanks a lot

**Comment by sbernard31** [comment] 2022-02-11 09:13
You're welcome

**Closed by sbernard31** 2022-02-11 09:13 UTC
Labels: question

**Comment by 18715001062** [comment] 2022-07-07 05:18
Dear leshan：

When I read and write object resources through the northbound API interface, request timeouts frequently occur.
Is this problem caused by frequent requests to the server, or is it caused by too small network bandwidth?

Thanks & Best Regards,

吴延平  Davis Wu | Software Testing Engineer | Quectel Wireless Solutions Co., Ltd.

Mobile: +86-187 1500 1062 | Email : ***@***.******@***.***>  | Tel: +86-551-65869386*8380
Website: www.quectel.com<http://www.quectel.com/>  | Wechat: wuyan1404618543

Building 1-C, China Speech Valley Area A, 3335 Xiyou Road, High-tech Zone, Hefei, Anhui 230088, China
安徽省合肥市高新区习友路3335号中国（合肥）国际智能语音产业园A区1号中试楼  230088

[6857b0ea042d04a447fdac6d7fa12cd2]
