### ISSUE TITLE
leshan bootstrap demo server could not verify the client x509 ceritification 

### ISSUE THREAD

**Issue by schSpring** [eclipse/leshan#960] opened 2021-01-21 02:52 UTC
I used leshan demo bootstrap server and leshan demo client to do the test using cert mode(x509), the bootstrap server could not verify the client certification.

The detailed process is 

- Start leshan demo bootstrap server:

   java -jar ./leshan-server-demo.jar -lh 192.168.1.114 -slh 192.168.1.114 -wh 192.168.1.414

- Generate client keys and certificate (self signed/CA signed all tested) following the guide https://github.com/eclipse/leshan/wiki/Credential-files-format

- Add client bootstrap configuration (x509 cert mode)

- Start leshan demo client with bootstrap certificate and client private key and certificate
java -jar ./leshan-client-demo.jar -n testca -b -u 192.168.1.133 -lh 192.168.1.123 -ccert ../ca_signed/ccert.der -scert ../bsServerCertificate.der -cprik ../ca_signed/cprik.der

The verification will fail, the log is 
_2021-01-20 17:00:35,601 INFO LeshanClient - Starting Leshan client ...
2021-01-20 17:00:35,623 INFO LeshanClient - Leshan client[endpoint:testca] started.
2021-01-20 17:00:35,626 INFO DefaultRegistrationEngine - Trying to start bootstrap session to coaps://192.168.1.133:5684 ...
2021-01-20 17:00:36,082 INFO CaliforniumEndpointsManager - New endpoint created for server coaps://192.168.1.133:5684 at coaps://192.168.1.123:46042
2021-01-20 17:00:36,280 INFO LeshanClientDemo - DTLS Full Handshake initiated by client : STARTED ...
2021-01-20 17:00:36,783 INFO LeshanClientDemo - DTLS Full Handshake initiated by client : FAILED (Received 'fatal alert/BAD_CERTIFICATE')
2021-01-20 17:00:36,783 INFO DefaultRegistrationEngine - Unable to send Bootstrap request : Received 'fatal alert/BAD_CERTIFICATE'
2021-01-20 17:00:36,790 INFO DefaultRegistrationEngine - Try to initiated bootstarp in 600s..._

We check with the wireshark data, the failure is happening in the DTLS hand-shake fifth step. In this step, client sends certificates to server for verify, and server returns an error: Bad Certificate.
![image](https://user-images.githubusercontent.com/77763770/105273609-a1c36c00-5bd6-11eb-8ea4-de1391125c9a.png)

Could you help on this problem? Thank you!

**Comment by sbernard31** [comment] 2021-01-21 10:07
Which version of Leshan are you using ?

**Comment by schSpring** [comment] 2021-01-21 13:40
We use the version 1.0.2

**Comment by sbernard31** [comment] 2021-01-21 13:46
Ok I will try to reproduce this.

**Comment by sbernard31** [comment] 2021-01-21 14:02
Regarding your order steps : 
-  Start leshan demo bootstrap server 
- Add client bootstrap configuration (x509 cert mode)
- Generate client keys and certificate (self signed/CA signed all tested) following the guide https://github.com/eclipse/leshan/wiki/Credential-files-format
- Start leshan demo client with bootstrap certificate and client private key and certificate

I have some concern about "adding client bootstrap config" before "generating client key and certificate". 
How to you fit fields below if you didn't generate credentials before ?
<img src="https://user-images.githubusercontent.com/840294/105360746-3939b680-5bf9-11eb-9d17-7f64c2b5848b.png" height=500 >

**Comment by schSpring** [comment] 2021-01-21 14:05
Sorry, the sequence need to change to be : generate first and add configuration after.

**Comment by schSpring** [comment] 2021-01-21 14:11
![image](https://user-images.githubusercontent.com/77763770/105361886-247b1400-5c35-11eb-8200-e5b798d76db9.png)
The configuration is configured after the certificate and private key is generated.  And using xxd -p -c 512 ccert.der and xxd -p -c 512 cprik.der to change to hex format to fill in the leshan bootstrap server configuration.

**Comment by sbernard31** [comment] 2021-01-21 14:12
Ok just tested with v1.0.2 following your steps and using self-signed certificate at client side and I succeed: 
```
2021-01-21 15:08:12,781 INFO LeshanClient - Starting Leshan client ...
2021-01-21 15:08:12,790 INFO LeshanClient - Leshan client[endpoint:issue_960] started.
2021-01-21 15:08:12,791 INFO DefaultRegistrationEngine - Trying to start bootstrap session to coaps://localhost:5684 ...
2021-01-21 15:08:12,905 INFO CaliforniumEndpointsManager - New endpoint created for server coaps://localhost:5684 at coaps://0.0.0.0:36820
2021-01-21 15:08:12,946 INFO LeshanClientDemo - DTLS Full Handshake initiated by client : STARTED ...
2021-01-21 15:08:13,033 INFO LeshanClientDemo - DTLS Full Handshake initiated by client : SUCCEED
2021-01-21 15:08:13,043 INFO DefaultRegistrationEngine - Bootstrap started

```

In bootstrap config you correctly copy past value from leshan-client-demo command line : 
```
java -jar leshan-client-demo-1.0.2-jar-with-dependencies.jar -scert bsServerCertificate.der -ccert self_signed_cert.der -cprik cprik.der -n issue_960 -b                                    ⏎
2021-01-21 15:08:12,780 INFO LeshanClientDemo - Client uses X509 : 
 X509 Certificate (Hex): 308202093 ... ... ... .... .... .... 537dc20b 
 Private Key (Hex): 308187020100 ... ... ... 29d82e2aceb7284f83f4e3ff8

```

**Comment by sbernard31** [comment] 2021-01-21 14:13
Using `xxd -p -c 512 cert.der` should work too. :thinking:

**Comment by schSpring** [comment] 2021-01-21 14:18
Could you specify some details on the configuration of leshan bootstrap server? If not use xxd -p -c 512 cert.der to get hex format, how could you fit the field on the web to configure? Maybe the problem is the configuration on our side.

**Comment by sbernard31** [comment] 2021-01-21 14:20
>  If not use xxd -p -c 512 cert.der to get hex format, how could you fit the field on the web to configure?

This is what I explained above, the leshan-demo-client log output give you the Hex value you can just copy/paste it.

**Comment by sbernard31** [comment] 2021-01-21 14:26
> Generate client keys and certificate (self signed/CA signed all tested) 

Could you first try to make it work with self-signed certificate at client side.
CA signed could be complicated. By the way if you plan to use CA signed certificate you should have a look at this https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/502 which is a kind of limitation of the LWM2M specification.

**Comment by sbernard31** [comment] 2021-01-21 14:41
I rethinking more about this but by default **leshan-bsserver-demo** should trust all certificate. (This is OK only for demo purpose)
So I'm not sure how a BAD_REQUEST could be generated ? :thinking: 
Unless you are using the `-truststore` option ?

**Comment by sbernard31** [comment] 2021-01-21 15:01
Maybe we can get more information if you activate some logs :https://github.com/eclipse/leshan/wiki/F.A.Q.#how-to-activate-more-log-

I guess `org.eclipse.californium.scandium.DTLSConnector` (or more radical `org.eclipse.californium.scandium.dtls`) in DEBUG or TRACE could help to understand the issue.

**Comment by schSpring** [comment] 2021-01-21 15:07
Thank you for all your information, I have just tested the self-signed certificate, and the bootstrap verification passed.

**Comment by schSpring** [comment] 2021-01-21 15:25
We will finally switch to CA signed certification, I will try to open logs to get more information on the CA certificate verification error.

**Comment by sbernard31** [comment] 2021-01-28 09:32
For CA signed certificate, I understand the only compatible way with LWM2M is with chain like this : 
"Root CA" -> "client Certificate"
(Because of https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/502 at least this is my understanding)

**Comment by sbernard31** [comment] 2021-01-28 09:33
Should we close this issue ?

**Comment by schSpring** [comment] 2021-01-28 10:53
OK. You could close this issue.

**Closed** 2021-01-28 10:57 UTC
Labels: question
