### ISSUE TITLE
Leshan server demo multiple value resource

### ISSUE THREAD

**Issue by RaiseYourChicken** [eclipse/leshan#1341] opened 2022-10-27 16:40 UTC
Currently there's an issue where if you read or observe a multiple value resource as a whole it succeeds, but if you try to read or observe instances inside said resource, the server fails when parsing the response payload

**Comment by sbernard31** [comment] 2022-10-28 07:18
Thx for reporting this. :pray: 

Could you share a more concrete use case so I will try to reproduce it.

**Comment by sbernard31** [comment] 2022-11-07 09:28
(Let me know if you plan to give us more details information about that)

**Comment by RaiseYourChicken** [comment] 2022-11-07 17:47
ah sorry, what do you need, I can share the leshan client I'm using to access the leshan sample server

**Comment by sbernard31** [comment] 2022-11-08 09:49
I need exact information or code to reproduce what you consider as an issue. :pray:

**Comment by sbernard31** [comment] 2022-11-25 09:01
I tried to reproduce  : 
 - with leshan demo (client and server )
 - version : `master` (3afc6382f0ca32592a762ada87bf0391609bd7e7)
 - on object 3442 and resource 1110 (Multiple String Value)
 - using content format TLV. 
 
 And it works for me. 

So, @RaiseYourChicken I would really appreciate if you could provide more detailed information : 
 - version used
 - what is used at client side and server side
 - which resource/resource instance you try to read/observe
 - which content format
 - maybe some logs or even a wireshark capture if needed.

I don't know, anything that could help to target the issue.

**Comment by sbernard31** [comment] 2022-12-15 10:10
@RaiseYourChicken I close this issue but please reopen it if you have any more information to share ... :disappointed:

**Closed by sbernard31** 2022-12-15 10:10 UTC
