### ISSUE TITLE
Real world IoT products using Leshan/LWM2M

### ISSUE THREAD

**Issue by rettichschnidi** [eclipse/leshan#853] opened 2020-06-15 08:38 UTC
I am doing some research for a new IoT platform/technology.

Reading issue #830/[Who is using](https://www.eclipse.org/leshan/#who%20is%20using)/[Adopters](https://iot.eclipse.org/adopters/) it seems like quite many organizations are using/offering Leshan as a platform. However, I could not find any actual products.

Are there any LWM2M (Leshan) IoT products on the marked (in stores) yet? Preferably in the consumer electronics area.

**Comment by sbernard31** [comment] 2020-06-15 08:49
It's really hard to us to get this informaiton as users don't let us know spontaneously when or for what they are using Leshan. That's why we try to get some answer with #830.

I haven't more information than the public one.

> Are there any LWM2M (Leshan) products on the marked yet?

The only one that I'm sure : [SierraWireless/Airvantage](https://www.sierrawireless.com/products-and-solutions/sims-connectivity-and-cloud-services/iot-cloud-platform/)

**Comment by fdesbiens** [comment] 2020-06-18 14:41
The Eclipse IoT website has a section where organizations can show their support for our projects. https://iot.eclipse.org/adopters. Self-reporting is the best we can do since our projects use permissive open source licenses.

**Comment by boaks** [comment] 2020-06-22 10:06
> Are there any LWM2M (Leshan) IoT products on the marked (in stores) yet? Preferably in the consumer electronics area.

As already mentioned by others above, it's not always visible, if leshan is used (nor is it visible, if Californium is used :-) ). 

For LwM2M it is more visible:
Some NB-IoT Modems of several manufacturers are offering LwM2M.
And [nbiot.engineering](https://nbiot.engineering) offers, among others, also LwM2M.

> Preferably in the consumer electronics area.

My feeling is, that currently products with coaps (openthread) starts to be available.

**Comment by sbernard31** [comment] 2020-08-28 09:15
Should we close this issue ? (knowing this is more or less a duplicate of #830)

**Comment by sbernard31** [comment] 2020-09-30 12:41
I close it but feel free to reopen if needed.

**Closed by sbernard31** 2020-09-30 12:41 UTC
Labels: question

**Comment by sbernard31** [comment] 2021-06-09 13:31
I found this recently https://github.com/thingsboard/thingsboard It seems it uses Leshan.
I never test it.
