### ISSUE TITLE
TLV encoding/decoding for data 

### ISSUE THREAD

**Issue by BenGant** [eclipse/leshan#65] opened 2016-01-22 15:01 UTC
As I see during TLV encoding/decoding for data format you do round modification(divide/multiply to 1000). I use mbed client  for connection to leshan. I fill resource "Current time" value by simple  "time" C function.When I read resource everything is okay, but if try to read all object instance: I got error:"Invalid content for type TIME".  Have I do this round modification(divide my current time by 1000) on client side or it is yours issue?

**Comment by sbernard31** [comment] 2016-01-26 16:29
The spec say that **Time** Datatype is : 
*Unix Time. A signed integer representing the number of seconds since Jan 1 st , 1970 in the UTC time zone.*
So Leshan expect that you send time in seconds.
We divide/multiply by 1000 because Java handles timestamp  in milliseconds. We do that for **TLV** and also for other encoding type like **TEXT** which is used when you made a read on resource.

Your  `time()` C function should return a `time_t`. The unit of `time_t` (seconds, milliseconds ...) is not defined by  C standard, so it depends of your implementation. I don't really know on this is implemented for your mbed, but generally `time_t` is in seconds...

I suspect the problem is at client side.

**Comment by BenGant** [comment] 2016-01-27 13:42
Thanks!

**Comment by sophokles73** [comment] 2016-01-27 14:15
@BenGant,

is this question answered from your point of view? Then it would be great if you would close the issue :-)

**Closed** 2016-01-27 14:19 UTC
Labels: question
