### ISSUE TITLE
Demo server is unable to create object instances

### ISSUE THREAD

**Issue by ptxmac** [eclipse/leshan#104] opened 2016-03-16 13:24 UTC
After Issue #75 (I think) the demo server can't create objects.

When using the "Create new instance" button I get the following error: 

Unable to create instance XXX : 400 Create request must target an object
Close

**Comment by sbernard31** [comment] 2016-03-16 13:37
Good catch !
(The issue is probably in [ClientServlet](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/servlet/ClientServlet.java#L262) and in [object-directives](https://github.com/eclipse/leshan/blob/master/leshan-server-demo/src/main/resources/webapp/js/object-directives.js#L65). We should remove the `instance` level  in the path)

**Comment by sbernard31** [comment] 2016-03-17 11:14
It should be fixed  in master since commit 273ca116757cefef1875c07b11082b0fea5a9083.

**Closed by sbernard31** 2016-03-17 11:14 UTC
Labels: bug
