### ISSUE TITLE
leshan demo server object version failure

### ISSUE THREAD

**Issue by davidahoward** [eclipse/leshan#1315] opened 2022-09-27 23:11 UTC
When I try connect to connect a lwm2m v1.1 client to leshan demo server I get an error relating to the object version 

Is this an ambiguity in the spec?

Sep 27 22:57:53 ip-172-31-61-197 java[14287]: 2022-09-27 22:57:53,186 RegisterResource     [TRACE] POST received : CON-POST   MID=16738, Token=B10001, OptionSet={"Uri-Path":"rd", "Content-Format":"application/link-format", "Uri-Query":["lt=60","lwm2m=1.1","ep=urn:dev:test-dh01"]}, "</3303/0>,</1/0>;ver=1.1,</3/0>;".. 39 bytes

Sep 27 22:57:53 ip-172-31-61-197 java[14287]: 2022-09-27 22:57:53,186 LwM2mCoapResource    [DEBUG] Invalid request [CON-POST   MID=16738, Token=B10001, OptionSet={"Uri-Path":"rd", "Content-Format":"application/link-format", "Uri-Query":["lt=60","lwm2m=1.1","ep=urn:dev:test-dh01"]}, "</3303/0>,</1/0>;ver=1.1,</3/0>;".. 39 bytes] received on the resource /rd from Identity /104.220.84.132:52204[psk=urn:dev:test-dh01]
Sep 27 22:57:53 ip-172-31-61-197 java[14287]: org.eclipse.leshan.core.link.LinkParseException: Unable to parse link </1/0>;ver=1.1 in </3303/0>,</1/0>;ver=1.1,</3/0>;ver=1.1

Sep 27 22:56:53 ip-172-31-61-197 java[14287]: Caused by: java.lang.IllegalArgumentException: ver attribute is only applicable to [OBJECT], and so can not be assigned to /1/0
Sep 27 22:56:53 ip-172-31-61-197 java[14287]:         at org.eclipse.leshan.core.link.lwm2m.attributes.MixedLwM2mAttributeSet.validate(MixedLwM2mAttributeSet.java:99)
Sep 27 22:56:53 ip-172-31-61-197 java[14287]:         at org.eclipse.leshan.core.link.lwm2m.DefaultLwM2mLinkParser.parseCoreLinkFormat(DefaultLwM2mLinkParser.java:149)

**Comment by davidahoward** [comment] 2022-09-28 02:53
There appears to be an ambiguity/error introduced in the specification between V1.1.1 and V1.2 with respect to Object versioning.

While neither specification appears to allow Object Instance versioning explicitly, V1.2 has an example that I believe is a typo that does show it.

 
https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#7-2-3-0-723-Object-Definition-and-Object-Version-Usage
 
7.2.3. Object Definition and Object Version Usage

At [OMNA], the Object ID:44 will be registered at least twice:
with the URN "urn:oma:lwm2m:oma:44" (version 1.0)
with the URN "urn:oma:lwm2m:oma:44:2.2"
 
An LwM2M Client supporting LwM2M Enabler version 1.0 registers this Object in version 2.2 along with the Server Object version 1.0 ("urn:oma:lwm2m:oma:1"), and the Device Object version 1.0 ("urn:oma:lwm2m:oma:3"). The registration payload is:
 
</1/0>,</1/1>,</3/0>,**</44/0>;ver=2.2**
 

<p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-size: 18pt;">Version: 1.1.1 - 2019 06 17</span></b><b><span style="font-size: 18pt;"><o:p></o:p></span></b></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><o:p> </o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><a href="https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#5-1-2-0-512-Attributes-Classification" contenteditable="false" title="https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#5-1-2-0-512-Attributes-Classification" style="color: rgb(5, 99, 193); text-decoration: underline;">https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#5-1-2-0-512-Attributes-Classification</a><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><o:p> </o:p></p>

Attribute Name | CoRE Link param | Attachment | Assignation Level | Support Required | Access Mode | Value Type | Default Value | Applicability | Notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Object Version | "ver" "=" 1*DIGIT "." 1*DIGIT | Object | Object | YES (Server) YES (Client) when able to support Objects in version > 1.0 | R | String | 1.0 (Initial Version) |   | Provides the version of the associated Object. The rules governing the usage of this parameter are specified in 7.2.3. Object Definition and Object Version Usage and Table: 7.2.3.-1 Object Version usage rules.

<p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><o:p> </o:p></p><br class="Apple-interchange-newline">Version: 1.1.1 - 2019 06 17
 
https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#5-1-2-0-512-Attributes-Classification

**Comment by sbernard31** [comment] 2022-09-29 14:45
If I correctly understand the issue this is about attaching `ver` attribute to an object instance.

The specification is pretty clear about this, the [version must be attached to object](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#Table-512-1-lessPROPERTIESgreater-Class-Attributes), correct ?

At https://github.com/eclipse/leshan/issues/1273#issuecomment-1261279899, you raise that there is an inconsistency in LWM2M v1.2 specification between attribute definition and example correct ?

When there is this kind of inconsistency, we think this is better to follow specification text body than example.
More than that here the inconsistency appears in LWM2M v1.2 and for now we do not support it :
- Leshan v1.x targets LWM2M v1.0.x
- Leshan v2.x targets LWM2M v1.1.x

So I think we are not concerned by this issue. 

Here is our  [thoughts about interoperability](https://github.com/eclipse/leshan/wiki/How-Leshan-should-behave-with-Non-Compliant-Implementations-%3F) (If you want to discuss about this general idea please open a dedicated issue)

Do you [open an issue about this at OMA](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues) ? or maybe you are member of OMA ?

**Comment by davidahoward** [comment] 2022-09-30 17:37
I work with two vice chairs of OMA... So yes, I've made them aware.  There is text being discussed to clarify this case - and it would allow the behavior.  It is, after-all, potentially more compact by a few bytes per object that is versioned.
I'm also trying to push for an update to the interop/test documentation from oma, and am looking forward to the interop events starting up again after the long covid hiatus.

**Comment by sbernard31** [comment] 2022-10-03 08:17
> here is text being discussed to clarify this case - and it would allow the behavior.

How this will affects the 1.0.x and 1.1.x  LWM2M version  ?

**Comment by sbernard31** [comment] 2022-12-15 10:03
I understand this will not affect LWM2M v1.0 or v1.2 so I think we can close it ?

**Comment by sbernard31** [comment] 2022-12-15 10:06
By the way, I feel this is a duplicate of #1273. So maybe better to close this one and continue discussion at #1273.

**Closed** 2022-12-15 10:08 UTC
Labels: discussion
